version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
