Skip to content
Navigation Menu
software-students-spring2025
5-final-final-hijimi

Type / to search
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
Settings
API CI/CD
Merge pull request #35 from software-students-spring2025/Shenrui-888 #100
Jobs
Run details
Workflow file for this run
.github/workflows/api.yml at 389eaef
# .github/workflows/api.yml  
name: API CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: '6.0'
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install API requirements
          pip install -r api/requirements.txt
          # Install recommender requirements as API depends on it
          pip install -r recommender/requirements.txt 
          # Install test dependencies
          pip install pytest pytest-cov httpx # httpx for testing FastAPI async client
        
      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$(pwd):$(pwd)/recommender
          pytest -v --cov=api api/tests/ --cov-report=xml --cov-report=term
      # Optional: Upload coverage report
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Build from root context to include recommender code if needed by Dockerfile COPY
          # Adjust Dockerfile COPY paths if building from root: COPY api/ /app, COPY recommender/ /app/recommender
          # For simplicity now, assuming API Dockerfile only copies api/
          # If Dockerfile needs recommender/, change context to '.' and adjust Dockerfile COPY
          file: ./api/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-api:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/xingjian1')
    steps:
      - name: Set up DO CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Needs DO access token
          
      - name: Deploy to DigitalOcean App Platform
        run: |
          echo "Deploying API to DO... (implement specific steps)"
          # Example: Trigger a deployment update for a DO App
          # Ensure you have doctl installed and configured, or use specific DO actions
          # doctl apps create-deployment <YOUR_APP_ID> --from-registry ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-api
          # Replace <YOUR_APP_ID> with your actual DigitalOcean App ID 
Merge pull request #35 from software-students-spring2025/Shenrui-888 · software-students-spring2025/5-final-final-hijimi@389eaef 
