name: Database CI/CD

on:
  push:
    branches: [ main , hy ]
    paths:
      - "database/**"
      - ".github/workflows/database.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: your-docker-hub-username
        password: ${{ secrets.DOCKERHUB_PAT }}

    - name: Build & push Mongo image
      uses: docker/build-push-action@v5
      with:
        context: ./database
        push: true
        tags: your-docker-hub-username/ecomm-mongo:${{ github.sha }}

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@v1.1.5     # ← 固定旧版
      with:
        app_name: ecomm-mongo                  # 你的 DO App 名
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: |
          - component_name: mongodb            # App 内服务组件名
            image: your-docker-hub-username/ecomm-mongo:${{ github.sha }}