name: Frontend CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies

      - name: Run build
        run: npm run build

      - name: Run linter
        run: npm run lint