name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/front.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check frontend files exist
        run: |
          test -f frontend/index.html && echo "index.html found"
