# .github/workflows/mongodb.yml
name: MongoDB CI/CD

on:
  push:
    branches:
      - main
      - master
      - xingjian1
    paths:
      - 'mongodb/**'
      - '.github/workflows/mongodb.yml'
  pull_request:
    branches:
      - main
      - master
      - xingjian1
    paths:
      - 'mongodb/**'
      - '.github/workflows/mongodb.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Needs to be configured in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Needs to be configured in GitHub Secrets

      - name: Build and push MongoDB image
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          file: ./mongodb/Dockerfile
          push: ${{ github.event_name == 'push' }} # Push only on push events to main/master
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-mongodb:latest # Replace with your Docker Hub username
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-mongodb:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-mongodb:buildcache,mode=max

  # Placeholder for deployment - Deploying MongoDB might involve:
  # - Using a managed MongoDB service on DigitalOcean
  # - Setting up a MongoDB instance on a Droplet (less common via simple Docker push)
  # This step assumes you might deploy this custom image to a container registry or orchestrator on DO.
  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
  #   steps:
  #     - name: Deploy to DigitalOcean (Placeholder)
  #       # Add steps to deploy using doctl, SSH, K8s manifests, etc.
  #       # This will highly depend on your DO infrastructure setup.
  #       run: echo "Deploying MongoDB (custom image) to DO... (implement specific steps)" 